[workspace]
members = [
    "examples/latex_test",
    "latex_gen",
    "server",
    "onnx",
    "hir"
]

[profile.release]
lto = true

[profile.bench]
debug = true

[profile.dev.package."*"]
opt-level = 3
