[workspace]
members = [
    "data",
    "linalg",
    "core",
    "hir",
    "nnef",
    "onnx-opl",
    "onnx",
    "examples/latex_test",
    "latex_gen",
    "server"
]

[profile.release]
lto = true

[profile.bench]
debug = true

[profile.dev.package."*"]
opt-level = 3
