[package]
name = "tract-hir"
version = "0.14.0"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
derive-new = "0.5"
educe = "0.4"
log = "0.4"
tract-core = "=0.14.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
env_logger = "0.8"
