[package]
name = "server"
version = "0.1.0"
authors = ["maxtnt <maxtnuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tract-onnx = { path = "../onnx",features=["latex"] }
actix-web = "3"
